### ISSUE TITLE
记录复现过程的一些问题——1.数据读取部分，pyedflib读取的采样率有问题

### ISSUE THREAD

**Issue by mx597014232** [dyzxzeng/TinySleepNet-pytorch#1]
n_epoch_samples = int(epoch_duration * sampling_rate)  
# 这里有问题，pyedflib读出来的采样率是3000，乘以30就是90000，实际上数据采样率只有100Hz
# 这会导致下一步.reshape(-1, n_epoch_samples) 报错

**Comment by mx597014232** [comment]
后面还有修改部分，涉及到那两个epoch为60秒的数据，稍微做了一下修改，程序不再报错了        
# 完整性检查
        n_epochs = psg_f.datarecords_in_file
        if psg_f.datarecord_duration == 60:  # Fix problems of SC4362F0-PSG.edf, SC4362FC-Hypnogram.edf
            n_epochs, epoch_duration = n_epochs * 2, epoch_duration // 2
            signals = signals.flatten().reshape(-1, n_epoch_samples // 2)
        assert len(signals) == n_epochs, f"signal: {signals.shape} != {n_epochs}"

**Comment by mx597014232** [comment]
def read_all_data_per_person(self, mypath="E:\\data\\sleepedf\\sleep-cassette\\eeg_fpz_cz"):
        file_list = [f for f in listdir(mypath) if isfile(join(mypath, f))]

        data_X, data_y = [], []
        for i in range(len(file_list)):  # len(file_list)
            **if file_list[i] == 'info_ch_extract.log':
                continue**
            with np.load(join(mypath, file_list[i]), allow_pickle=True) as npz:
                data_X.append(npz['x'])
                data_y.append(npz['y'])

# 由于目录下还包含log文件，读取会报错，可以删除log，或者加个条件判断跳过log文件。
#  np.load 加上 allow_pickle=True

**Comment by mx597014232** [comment]
self.X_1epoch = np.array(self.X_1epoch)[:, :, np.newaxis]
        self.y_1epoch = np.array(self.y_1epoch)
        self.X_seq = np.array(self.X_seq)[:, :, :, np.newaxis]
        self.y_seq = np.array(self.y_seq)

# self.X_1epoch 缺了一个维度，加上np.newaxis 。

**Comment by mx597014232** [comment]
def forward(self, x):
        signal = x
        signal = self.conv1(signal)
        signal = self.bn1(signal)
        signal = self.relu1(signal)
        # signal = self.dropout(signal)
        signal = self.conv2(signal)
        signal = self.bn2(signal)
        signal = self.relu2(signal)

        if self.stride!=1:
            x = self.maxpool(x)
        signal = signal += x  # error!!!!!!!!
        # print('signal',signal.shape)
        return signal

# signal += x的写法会报错！影响到pytorch求梯度了！
# 应该更正为 signal = signal + x

**Comment by zhangmubei** [comment]
Traceback (most recent call last):
  File "D:\pythonProject-torch\Automatic-Sleep-Staging-Based-on-EEG-Signal-using-Deep-Network-main\preprocessing.py", line 141, in <module>
    x, y = edf2numpy(signal_file_path, annotation_file_path, select_channels=["EEG Fpz-Cz"])
  File "D:\pythonProject-torch\Automatic-Sleep-Staging-Based-on-EEG-Signal-using-Deep-Network-main\preprocessing.py", line 69, in edf2numpy
    assert signals.shape[0] == n_epochs, f"signal: {signals.shape} != {n_epochs}"
AssertionError: signal: (79500, 100) != 2650
报错这个是怎么解决的
